### ISSUE TITLE
Разработка на TypeScript

### ISSUE THREAD

**Issue by nodkz** [xx3u/portfolio#17]
Юлия, добрый день.

Напишите мне пожалуйста в теграмм @nodkz
Мы ищем разработчиков на JS в ps.kz

Спасибо.

**Comment by nodkz** [comment]
Предложение временно снимается. 
Оказывается у вас есть договоренность с преподавателем.

**Comment by xx3u** [comment]
Добрый день, Павел. Только увидела сообщения. Насчет каки-либо договоренностей лучше спрашивать лично меня. Спасибо за предложение)

**Comment by nodkz** [comment]
Так или иначе можем познакомиться и пообщаться голосом. Будет время - найдите меня в телеграме @nodkz
